//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPurchase
    {
        public int DPurID { get; set; }
        public Nullable<int> MPurID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ProDes { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> SubTotl { get; set; }
        public Nullable<double> SaleTax { get; set; }
        public Nullable<double> NetTotal { get; set; }
        public string Unit { get; set; }
        public Nullable<double> Cost { get; set; }
        public string ProTyp { get; set; }
        public Nullable<int> GrossTtal { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CompanyId { get; set; }
        public string BranchId { get; set; }
        public Nullable<int> pckts { get; set; }
        public Nullable<int> cartons { get; set; }
        public Nullable<double> Amount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual MPurchase MPurchase { get; set; }
        public virtual Product Product1 { get; set; }
        public virtual MPurchase MPurchase1 { get; set; }
    }
}
