//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class DsrStock
    {
        public int DsrStockid { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> DsrQuantity { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<int> RemainingQuantity { get; set; }
    }
}
