//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mpos
    {
        public int Mposid { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> BiLLdate { get; set; }
        public Nullable<double> AmountPaid { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<bool> C_17Per { get; set; }
        public Nullable<bool> C_3Per { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public string CustomerName { get; set; }
        public string CellNo { get; set; }
        public string Per17Amt { get; set; }
        public string Per3Amt { get; set; }
        public Nullable<double> Amount { get; set; }
    }
}
