//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salereturn
    {
        public int SaleReturnId { get; set; }
        public string InvoiceNumber { get; set; }
        public string ReturnType { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> ReturnTypeId { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
    }
}
