//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalereturnChild
    {
        public int SalereturnChild1 { get; set; }
        public Nullable<int> SaleReturnId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ProductQty { get; set; }
        public Nullable<double> productCost { get; set; }
        public Nullable<double> ProductAmt { get; set; }
    }
}
