//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public int supplierId { get; set; }
        public string suppliername { get; set; }
        public string contactperson { get; set; }
        public string BackUpContact { get; set; }
        public string City_ { get; set; }
        public string phoneno { get; set; }
        public string mobile { get; set; }
        public string faxno { get; set; }
        public string postalcode { get; set; }
        public string designation { get; set; }
        public string AddressOne { get; set; }
        public string AddressTwo { get; set; }
        public string CNIC { get; set; }
        public string Url { get; set; }
        public string BusinessNature { get; set; }
        public string Email { get; set; }
        public string NTNNTRNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Sup_Code { get; set; }
        public string CompanyId { get; set; }
        public string BranchId { get; set; }
        public string sup_acc { get; set; }
        public Nullable<double> prebal { get; set; }
        public Nullable<int> Limit { get; set; }
    }
}
