//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee
    {
        public int employeeID { get; set; }
        public string employeeName { get; set; }
        public string employeeLastName { get; set; }
        public string employeeFatherName { get; set; }
        public string CategoryID { get; set; }
        public Nullable<int> EmployeeType { get; set; }
        public string Qualification { get; set; }
        public string CNIC { get; set; }
        public string CityID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PhoneNum { get; set; }
        public string CellNum { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Passport { get; set; }
        public string Email { get; set; }
        public string PostalCode { get; set; }
        public string MarkID { get; set; }
        public string Gender { get; set; }
        public string Disability { get; set; }
        public string NTN { get; set; }
        public string Religion { get; set; }
        public string ConvcenceAllowance_Day { get; set; }
        public string ConvcenceAllowance_Km { get; set; }
        public string SalesPercentage { get; set; }
        public string NetSalary { get; set; }
        public string RMSID { get; set; }
        public string RSMPercentage { get; set; }
        public Nullable<bool> EmployeeCardExits { get; set; }
        public Nullable<bool> EmployeeCardPrinted { get; set; }
        public string COAID { get; set; }
        public Nullable<bool> IsSalman { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public string Created_By { get; set; }
        public string designation { get; set; }
        public string Address { get; set; }
        public Nullable<double> income_tax { get; set; }
        public string others { get; set; }
        public string incentive { get; set; }
        public string Entertainment { get; set; }
        public Nullable<int> Depart_id { get; set; }
        public string emp_acc { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
