//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_vchtyp
    {
        public int vchtyp_id { get; set; }
        public string vchtyp_nam { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> PayTyp_id { get; set; }
    
        public virtual tbl_PayTyp tbl_PayTyp { get; set; }
        public virtual tbl_PayTyp tbl_PayTyp1 { get; set; }
    }
}
