//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealBoxCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dpos
    {
        public int Dposid { get; set; }
        public Nullable<int> Productid { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
        public Nullable<double> productPrice { get; set; }
        public Nullable<double> ProductAmount { get; set; }
        public Nullable<int> Mposid { get; set; }
    }
}
