//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealBoxCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Head
    {
        public int HeadID { get; set; }
        public string HeadName { get; set; }
        public string HeadGeneratedID { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string HeadKey { get; set; }
        public string CompanyId { get; set; }
        public string BranchId { get; set; }
        public string Type { get; set; }
    }
}
