//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealBoxCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPurchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MPurchase()
        {
            this.DPurchases = new HashSet<DPurchase>();
            this.DPurchases1 = new HashSet<DPurchase>();
        }
    
        public int MPurID { get; set; }
        public string VndrNam { get; set; }
        public string VndrAdd { get; set; }
        public string VndrCntct { get; set; }
        public string PurNo { get; set; }
        public Nullable<System.DateTime> MPurDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CNIC { get; set; }
        public string NTNNo { get; set; }
        public Nullable<bool> ToBePrntd { get; set; }
        public Nullable<bool> ck_Act { get; set; }
        public string MPurRmk { get; set; }
        public Nullable<int> ven_id { get; set; }
        public Nullable<int> PayTyp_id { get; set; }
        public Nullable<int> vchtyp_id { get; set; }
        public Nullable<double> csh_amt { get; set; }
        public Nullable<int> CashBnk_id { get; set; }
        public Nullable<int> chque_No { get; set; }
        public Nullable<int> subheadcategoryfourID { get; set; }
        public Nullable<double> Out_Standing { get; set; }
        public Nullable<double> grssttl { get; set; }
        public string CompanyId { get; set; }
        public string BranchId { get; set; }
        public string DCNO { get; set; }
        public string DatTim { get; set; }
        public string BiltyNo { get; set; }
        public string VehicalNo { get; set; }
        public string DriverNam { get; set; }
        public string DriverMobilno { get; set; }
        public string Transporter { get; set; }
        public string station { get; set; }
        public string DilverOrdr { get; set; }
        public Nullable<double> frieght { get; set; }
        public Nullable<double> NetTotal { get; set; }
        public Nullable<double> GrossTtal { get; set; }
        public string PayAcc { get; set; }
        public Nullable<bool> Effected { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> PrevBal { get; set; }
        public Nullable<int> WareHouseid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPurchase> DPurchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPurchase> DPurchases1 { get; set; }
        public virtual VoucherType VoucherType { get; set; }
    }
}
