//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealBoxCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleCreadit
    {
        public int SaleCreaditId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<double> CreaditAmount { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<int> insertedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> InsertedAt { get; set; }
    }
}
