//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealBoxCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ddsrbk
    {
        public int dsrid { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> untid { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> salrat { get; set; }
        public Nullable<double> salrturn { get; set; }
        public Nullable<double> recvry { get; set; }
        public Nullable<double> outstan { get; set; }
        public Nullable<double> Amt { get; set; }
        public string dsrrmk { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<double> ttlamt { get; set; }
        public Nullable<double> finlqry { get; set; }
        public Nullable<System.DateTime> DsrDate { get; set; }
        public Nullable<int> MdsrId { get; set; }
        public Nullable<int> DsrBookid { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual tbl_unts tbl_unts { get; set; }
    }
}
