//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealBoxCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CB
    {
        public int CB_id { get; set; }
        public string CB_sono { get; set; }
        public Nullable<System.DateTime> CB_dat { get; set; }
        public Nullable<int> CBPartiID { get; set; }
        public Nullable<double> CBCrAmt { get; set; }
        public Nullable<double> CBDBAmt { get; set; }
        public Nullable<double> CBTtlCrAmt { get; set; }
        public Nullable<double> CBTtlDBAmt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<bool> ISActive { get; set; }
        public Nullable<double> AmountVar { get; set; }
    }
}
