//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealBoxCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HoldDPso
    {
        public int HoldDPsoid { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ProductQuntity { get; set; }
        public Nullable<double> ProductPrice { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<int> HoldMposid { get; set; }
    
        public virtual tbl_HoldMPso tbl_HoldMPso { get; set; }
    }
}
