//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealBoxCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DSal
    {
        public int DSal_id { get; set; }
        public string DSal_ItmDes { get; set; }
        public Nullable<int> DSal_ItmQty { get; set; }
        public string DSal_ItmUnt { get; set; }
        public Nullable<double> DSal_salcst { get; set; }
        public Nullable<double> DSal_netttl { get; set; }
        public Nullable<double> DSal_ttl { get; set; }
        public Nullable<int> MSal_id { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<double> Dis { get; set; }
        public Nullable<double> rat { get; set; }
        public Nullable<double> Amt { get; set; }
        public Nullable<double> GST { get; set; }
        public Nullable<double> GTtl { get; set; }
        public string CompanyId { get; set; }
        public string BranchId { get; set; }
        public Nullable<int> pckts { get; set; }
        public Nullable<int> cartons { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual tbl_MSal tbl_MSal { get; set; }
    }
}
