//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealBoxCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MPos
    {
        public int Mposid { get; set; }
        public string BillNO { get; set; }
        public string CompanyId { get; set; }
        public string BranchId { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> billdat { get; set; }
        public Nullable<System.TimeSpan> billtim { get; set; }
        public string CustomerName { get; set; }
        public string CellNo1 { get; set; }
        public Nullable<int> custtyp { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createdat { get; set; }
        public string createterminal { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> updatedat { get; set; }
        public string updateterminal { get; set; }
        public Nullable<bool> C17Per { get; set; }
        public Nullable<bool> C3Per { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<double> AmountPaid { get; set; }
    }
}
