//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealBoxCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Mdsr
    {
        public int dsrid { get; set; }
        public Nullable<System.DateTime> dsrdat { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<bool> Isdone { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string CreateBy { get; set; }
        public string Username { get; set; }
        public Nullable<double> saleper { get; set; }
        public Nullable<double> prevbal { get; set; }
        public Nullable<int> Salesman { get; set; }
        public Nullable<int> areaid { get; set; }
        public Nullable<double> furout { get; set; }
        public string updateBy { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<int> Discount { get; set; }
        public string DsrRemarks { get; set; }
        public Nullable<double> TotalAfterdis { get; set; }
        public Nullable<int> BookerId { get; set; }
    }
}
