//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealBoxCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MSal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_MSal()
        {
            this.tbl_DSal = new HashSet<tbl_DSal>();
        }
    
        public int MSal_id { get; set; }
        public string MSal_sono { get; set; }
        public Nullable<System.DateTime> MSal_dat { get; set; }
        public string MSal_Rmk { get; set; }
        public Nullable<int> MSalOrdid { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<bool> ISActive { get; set; }
        public Nullable<bool> iscre { get; set; }
        public Nullable<bool> iscash { get; set; }
        public string gatpassno { get; set; }
        public string schm { get; set; }
        public string bons { get; set; }
        public Nullable<double> Recovery { get; set; }
        public Nullable<double> Outstanding { get; set; }
        public string CompanyId { get; set; }
        public string BranchId { get; set; }
        public string username { get; set; }
        public string Booker { get; set; }
        public string SalMan { get; set; }
        public Nullable<int> promethod { get; set; }
        public Nullable<int> MProQuot_id { get; set; }
        public string custacc { get; set; }
        public Nullable<double> gst { get; set; }
        public Nullable<double> othtax { get; set; }
        public Nullable<double> Amt { get; set; }
        public Nullable<double> GTtl { get; set; }
        public Nullable<double> Dis { get; set; }
        public Nullable<double> sdis { get; set; }
        public Nullable<double> sdisamt { get; set; }
        public Nullable<double> netttlcash { get; set; }
        public Nullable<bool> Effected { get; set; }
        public Nullable<double> PrevBalance { get; set; }
        public Nullable<int> ApplyDis { get; set; }
        public Nullable<double> ApplyDiscAmt { get; set; }
        public Nullable<int> WareHouseId { get; set; }
    
        public virtual Customers_ Customers_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DSal> tbl_DSal { get; set; }
    }
}
