//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealBoxCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SubMenu
    {
        public int SubMenuId { get; set; }
        public string SubMenuNam { get; set; }
        public string SubMenuDesc { get; set; }
        public string SubMenuUrl { get; set; }
        public Nullable<bool> Isview { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> MenuId { get; set; }
    
        public virtual tbl_Menu tbl_Menu { get; set; }
    }
}
